### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by NgbatzYT** [zaynethedev/GorillaSteps#1]
it doeasnt worjf befacsuese to u fuckedfc up thde c poedlard

**Comment by zaynethedev** [comment]
![Uploading joe.png…]()

**Comment by zaynethedev** [comment]
![joe](https://github.com/user-attachments/assets/a61cad46-f49b-47f6-aa3f-e63b65fc1ce1)

**Comment by NgbatzYT** [comment]
> ![joe](https://private-user-images.githubusercontent.com/142189531/398247501-a61cad46-f49b-47f6-aa3f-e63b65fc1ce1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5ODQyODcsIm5iZiI6MTczNDk4Mzk4NywicGF0aCI6Ii8xNDIxODk1MzEvMzk4MjQ3NTAxLWE2MWNhZDQ2LWY0OWItNDdmNi1hYTNmLWU2M2I2NWZjMWNlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxOTU5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGY2OGVjMmNlMjdhZTlhMWE3ZDRjYmEzMzY4NmViMzE0MmZiZjRhZTgyN2I3M2UxNWFhMWMyZTQ0YTU0ODYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UtDOy9dRtJgb9Zg1cH2tv2-33RGFhAajyz5NjU7f7BQ)

thysi is verdyhfc x offfehnsderf forf  me dbeaqcaue i am thnend aparier m an

**Comment by zaynethedev** [comment]
![jork](https://github.com/user-attachments/assets/5bc77a85-5056-4b05-b725-b670593e7df7)
