### ISSUE TITLE
The wastch dosent work

### ISSUE THREAD

**Issue by masterpigeon11** [zaynethedev/GorillaSteps#6]
the watch seems to track the steps of the entire lobby but it dosent work in privates. its basically unusable also because the steps dont reset after you disconnect or in any other way

**Comment by zaynethedev** [comment]
The watch should work in privates, but I'll get to that, and the steps aren't supposed to reset. They save.

**Comment by masterpigeon11** [comment]
ok thank you for your awesome mods

**Comment by zaynethedev** [comment]
np man
